use_frameworks!

def default_pods
    pod 'Scaffold', :path => '../'
end


target 'Scaffold_Example' do
    default_pods
end

target 'Scaffold_Tests' do
    inherit! :search_paths
    default_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
