osx_image: xcode8.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
    - gem install cocoapods # Since Travis is not always on latest version
    - pod install --project-directory=Example

script:
    - xcodebuild test -workspace Example/Scaffold.xcworkspace -scheme Scaffold-Example -configuration Debug ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3' | xcpretty;
